### ISSUE TITLE
Unable to locate element {"method":"css selector","selector":"[id="duo_iframe"]"}

### ISSUE THREAD

**Issue by ScGong04** [Svision/UofT_CourseScript#6]
Hi, while I was trying to run the script the chrome always close automatically once the acorn is opened. I am not sure if that's the page is refreshing or its just not working properly.

**Comment by ScGong04** [comment]
Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="duo_iframe"]"}
  (Session info: chrome=120.0.6099.234); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception

**Comment by Svision** [comment]
Hi, I also received others reporting this issue, but unfortunately, I do not have any account that can reproduce the issue. Please make sure you did not set an automatic push DUO notification, and if possible, please create a PR to fix the issue since you can reproduce it. Thank you!
